import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/ManualControl.module.css";
import { Joystick } from "react-joystick-component";
import { useEffect, useState } from "react";

function ManualControl() {
  const [move, setMove] = useState({ direcao: 0, velocidade: 0 });
  const submitMove = async () => {
    const response = await fetch("/api/control", {
      method: "POST",
      body: JSON.stringify({ move }),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data = await response.json();
    console.log(data);
  };

  useEffect(() => {
    submitMove();
  }, [move]);

  const handleMove = (e) => {
    const direcao = parseInt(Math.atan2(e.x, e.y) * (180 / Math.PI));
    setMove({
      direcao: direcao,
      velocidade: parseInt((Math.sqrt(e.x * e.x + e.y * e.y) * 100) / 50),
    });
  };
  const handleStop = (e) => {
    setMove({ direcao: 0, velocidade: 0 });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">Home</Link>
        <h1>Controle manual!</h1>
        <Joystick
          size={100}
          baseColor="black"
          stickColor="red"
          move={handleMove}
          stop={handleStop}
        />
        <div className={styles.info}>
          <p>Direção: {move.direcao}</p>
          <p>Velocidade: {move.velocidade}</p>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
export default ManualControl;
