import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Dashboard() {
  const [coordinate, setCoordinate] = useState("");
  const submitCoordinate = async () => {
    const response = await fetch("/api/coordinates", {
      method: "POST",
      body: JSON.stringify({ coordinate }),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data = await response.json();
    console.log(data);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Teste POST!</h1>
        <input
          type="text"
          value={coordinate}
          onChange={(e) => setCoordinate(e.target.value)}
        />
        <button onClick={submitCoordinate}>Submit</button>
        {coordinate}
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
